# Generated by Django 6.0.5 on 2026-06-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_category_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processimage',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='image',
        ),
        migrations.AddField(
            model_name='assetitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/'),
        ),
        migrations.AddField(
            model_name='processimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='processes/images/'),
        ),
    ]
