# Generated by Django 6.0.5 on 2026-06-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_remove_processimage_img_url_remove_workflow_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
    ]
