# Generated by Django 6.0.5 on 2026-06-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_remove_assetitem_status_remove_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetitem',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
