# Generated by Django 6.0.5 on 2026-06-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_assetitem_status_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processimage',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='processes/images/'),
        ),
    ]
