# Generated by Django 6.0.5 on 2026-06-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_alter_processimage_image_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('workflow', 'step')},
        ),
    ]
