# Generated by Django 6.0.5 on 2026-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_alter_process_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='workflows/videos/'),
        ),
    ]
