# Generated by Django 6.0.5 on 2026-06-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_workflow_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='workflows/documents/'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='workflows/images/'),
        ),
    ]
