# Generated by Django 6.0.5 on 2026-06-18 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_workflow_document_file_workflow_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='video_file',
        ),
        migrations.CreateModel(
            name='WorkflowFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='workflows/files/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='processes.workflow')),
            ],
        ),
    ]
