# Generated by Django 6.0.5 on 2026-06-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0010_remove_workflow_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitem',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='assets/images/'),
        ),
        migrations.AlterField(
            model_name='processimage',
            name='image_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='processes/images/'),
        ),
        migrations.AlterField(
            model_name='workflowfile',
            name='file',
            field=models.FileField(max_length=500, upload_to='workflows/files/'),
        ),
    ]
