# Generated by Django 6.0.5 on 2026-06-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimage',
            name='img_url',
            field=models.ImageField(max_length=1000, upload_to=''),
        ),
    ]
