# Generated by Django 6.0.5 on 2026-06-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_commentimage_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimage',
            name='img_url',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
    ]
