# Generated by Django 6.0.5 on 2026-06-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notif_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
